Feat/mylikes
benhurfaria/projeto_11_linkr pull request #12
Opened 2021-09-20 23:38 UTC by benhurfaria

- na rota /mylikes foi implementado para ver os posts q o usuario deu like

2021-09-21 15:16 UTC, sidneyouteiro commented
o react-tooltip não está sendo aplicado na página my-likes

2021-09-21 15:16 UTC, sidneyouteiro requested changes
o react-tooltip não está sendo aplicado na tela /my-likes

2021-09-22 19:32 UTC, Audamon approved these changes
Acho que está ok

2021-09-24 12:53 UTC, sidneyouteiro approved these changes

2021-09-24 12:53 UTC, merged