Fix/likes
benhurfaria/projeto_11_linkr pull request #13
Opened 2021-09-22 01:11 UTC by Audamon

- Likes fix

2021-09-22 02:31 UTC, teles-tarcisio commented
@Audamon , tá dando que não tem conflito, mas não tá passando no vercel. tu sabes qual o erro?

2021-09-22 19:41 UTC, benhurfaria approved these changes

2021-09-23 18:44 UTC, teles-tarcisio commented
@Audamon , to vendo umas broncas ainda:
- qdo um post nao tem likes, não exibe o balãozinho, ok;
- somente com o "meu" like, tbm exibe certo;
- posts com + de 3 likes parece que tá com bronca:
![image](https://user-images.githubusercontent.com/38328194/134565423-483edb7c-4713-4303-b436-069a11ccf510.png)
![image](https://user-images.githubusercontent.com/38328194/134565520-d61aca59-229c-4e00-8839-02807dfd5202.png)

2021-09-24 12:27 UTC, sidneyouteiro requested changes

2021-09-24 12:27 UTC, sidneyouteiro commented on src/Login/Login.js
> +        }
`user ? history.push("/timeline") : history.push('/')`

2021-09-24 12:27 UTC, sidneyouteiro commented on src/SignUp/SignUp.js
> +        }
`user ? history.push("/timeline") : history.push('/signup')`

2021-09-24 12:27 UTC, sidneyouteiro commented on src/Timeline/PostsList/Likes/PeoplesLikes.js
> +export { peoplesLikes }
Seria uma boa reescrever esse trecho de código, pois por mais que dê para cobrir cada caso é difícil compreender ele. E provavelmente nem algum erro na lógica, como foi apontado pelo tarcisio na aba de conversação. Talvez seja algo relacionado a algum useState que não está sendo settado devidamente.

2021-09-25 08:57 UTC, sidneyouteiro requested changes
Acredito que as modificações realizadas na função peopleslikes acabou gerando um comportamento inesperado. Quando eu curto e descurto um post que tem mais de 3 likes isso acontece:
![image](https://user-images.githubusercontent.com/44553251/134765817-7133c9c9-c4b4-4fe2-8343-9a2aadc048d2.png)
![image](https://user-images.githubusercontent.com/44553251/134765824-218a6b5b-0df1-4755-8330-9a4f0dfee6f8.png)
![image](https://user-images.githubusercontent.com/44553251/134765833-7ae10d03-00e4-4bfb-91f8-a6933fd10b04.png)

2021-09-27 17:32 UTC, benhurfaria approved these changes

2021-09-27 17:51 UTC, sidneyouteiro approved these changes

2021-09-27 17:51 UTC, merged