Feat /user/user
benhurfaria/projeto_11_linkr pull request #14
Opened 2021-09-22 02:22 UTC by teles-tarcisio

@Audamon @benhurfaria

2021-09-22 17:02 UTC, Audamon commented
Acho que está ok

2021-09-22 19:50 UTC, Audamon approved these changes
Parece ok

2021-09-24 12:49 UTC, sidneyouteiro requested changes

2021-09-24 12:49 UTC, sidneyouteiro commented on src/UserIDPosts/UserIDPosts.js
> +        }
```
if (!response.data.posts.length) {
            alert("Nenhum post encontrado");
            return;
        }
```

2021-09-24 12:49 UTC, sidneyouteiro commented on src/UserIDPosts/UserIDPosts.js
> +        console.log(response.data);
Opa, `console.log` perdido

2021-09-24 12:49 UTC, sidneyouteiro commented on src/UserIDPosts/UserIDPosts.js
> +                        <h1>{(postsLoaded === true) ? `${postsArray[0].user.username}'s posts` : ""}</h1>
`{postsLoaded && '${postsArray[0].user.username}'s posts'}`

2021-09-24 12:49 UTC, sidneyouteiro commented on src/Timeline/PostsList/PostsList.js
> +        }
No longo prazo essa estrutura desse componente na totalidade não apresentará muito ganho há casos em que estruturar dessa forma não há problemas, contudo quando começa a ser necessário transformar o componente em um "canivete suíço" pode acabar complicando mais do que ajudando. Uma refatoração futura (no momento acredito que pode quebrar complicar em conflito de merge) seria montar a listagem de posts em cada componente conforme a necessidade assim eliminaria a necessidade de ter um componente para gerenciar isso e facilitaria na hora de mapear possiveis problemas. Caso queira trocar uma ideia mais aprofundada sobre isso só chamar 🤙🏽

2021-09-24 12:49 UTC, sidneyouteiro commented on src/MyPosts/MyPosts.js
> +        }
`if (!response.data.posts.length)`

2021-09-24 13:56 UTC, teles-tarcisio commented on src/Timeline/PostsList/PostsList.js
> +        }
OK Sidney, ciente. Melhor eles isolados mesmo, tanto é que da timeline pra hashtag e userid deixei mais separado um pouco pra realmente isolar todos depois

2021-09-24 14:32 UTC, teles-tarcisio commented on src/UserIDPosts/UserIDPosts.js
> +        }
done

2021-09-24 14:32 UTC, teles-tarcisio commented on src/UserIDPosts/UserIDPosts.js
> +        console.log(response.data);
deleted

2021-09-24 14:33 UTC, teles-tarcisio commented on src/UserIDPosts/UserIDPosts.js
> +                        <h1>{(postsLoaded === true) ? `${postsArray[0].user.username}'s posts` : ""}</h1>
done

2021-09-24 14:33 UTC, teles-tarcisio commented on src/MyPosts/MyPosts.js
> +        }
done

2021-09-25 09:06 UTC, sidneyouteiro requested changes

2021-09-25 09:06 UTC, sidneyouteiro commented on src/HashtagPosts/HashtagPosts.js
> +        console.log(response.data);
`console.log` perdido

2021-09-25 09:06 UTC, sidneyouteiro commented on src/HashtagPosts/HashtagPosts.js
> +    console.log("#:", hashtagParam.hashtagid);
`console.log` perdido

2021-09-25 09:06 UTC, sidneyouteiro commented on src/Timeline/PostsList/PostsList.js
> +                </>
O que eu quis dizer na conversa anterior é que esse trecho poderia ir direto para o componente `UserIDPosts.js` assim evitaria/minimizaria o efeito de tudo ir para um mesmo canto (no caso tudo ir para o `PostsList.js`)

2021-09-25 09:06 UTC, sidneyouteiro commented on src/HashtagPosts/HashtagPosts.js
> +                </TimelineHeader>
O componente `Topbar` deveria ser utilizado aqui

2021-09-25 09:06 UTC, sidneyouteiro commented on src/UserIDPosts/UserIDPosts.js
> +                </TimelineHeader>
O componente `Topbar` deveria ser utilizado aqui

2021-09-25 09:06 UTC, sidneyouteiro commented on src/App.js
> +                            <Timeline />
A página `my-likes` parou de funcionar com essa mudança

2021-09-25 09:06 UTC, sidneyouteiro commented on src/MyPosts/MyPosts.js
> +                </TimelineHeader>
O componente `Topbar` deveria ser utilizado aqui

2021-09-25 22:22 UTC, teles-tarcisio commented on src/HashtagPosts/HashtagPosts.js
> +        console.log(response.data);
deleted

2021-09-25 22:23 UTC, teles-tarcisio commented on src/Timeline/PostsList/PostsList.js
> +                </>
ciente, mas nao modifiquei agora para nao quebrar o restante das coisas

2021-09-25 22:23 UTC, teles-tarcisio commented on src/HashtagPosts/HashtagPosts.js
> +                </TimelineHeader>
fixed

2021-09-25 22:23 UTC, teles-tarcisio commented on src/App.js
> +                            <Timeline />
fixed, pending retest

2021-09-25 22:23 UTC, teles-tarcisio commented on src/MyPosts/MyPosts.js
> +                </TimelineHeader>
fixed

2021-09-25 22:46 UTC, teles-tarcisio commented on src/HashtagPosts/HashtagPosts.js
> +    console.log("#:", hashtagParam.hashtagid);
deleted

2021-09-25 22:46 UTC, teles-tarcisio commented on src/UserIDPosts/UserIDPosts.js
> +                </TimelineHeader>
fixed

2021-09-26 22:12 UTC, benhurfaria approved these changes

2021-09-27 01:46 UTC, sidneyouteiro approved these changes

2021-09-27 01:47 UTC, merged