feat/apagar
benhurfaria/projeto_11_linkr pull request #17
Opened 2021-09-22 04:15 UTC by benhurfaria

-feito as funcoes para deletar o proprio post

2021-09-23 19:17 UTC, teles-tarcisio commented
@benhurfaria , aparentemente tudo funcionando, não encontrei erros nuns 4 testes aqui. tu podes conferir esse conflito que tá dando aí?

2021-09-23 23:04 UTC, teles-tarcisio commented
retestei, não consegui achar mais erros. vamo esperar por Sidney

2021-09-23 23:06 UTC, teles-tarcisio approved these changes

2021-09-24 12:14 UTC, sidneyouteiro requested changes

2021-09-24 12:14 UTC, sidneyouteiro commented on src/Timeline/PostsList/SinglePost.js
> +                        }
```
{linkImage &&  <img src={linkImage} alt="thumbnail" />}
```

2021-09-24 12:14 UTC, sidneyouteiro commented on src/Timeline/PostsList/SinglePost.js
> +        apagarPost(config, id, setIsModalVisible, setPostsArray, postsArray);
Acredito que seja uma boa retornamos a promise e deixar o `.then` e o `.catch` dentro dessa função para seguir o padrão nos demais componentes.

2021-09-24 12:14 UTC, sidneyouteiro commented on src/services/api/Api.js
> +        })
Poderíamos aplicar a comparação feita na função `retirar` direto  com uma alteração no filter. Exemplo:
`postsArray.filter((arr) => arr.id !== id)` geraria o mesmo retorno.

2021-09-24 12:14 UTC, sidneyouteiro commented on src/services/api/Api.js
> +            setPostsArray(postsArray.filter((arr) => retirar(arr.id, id)));
É ideal evitarmos encadear uma função na outra. Poderíamos colocar o resultado do filter em uma variável e em seguida passa-la para o `setPostsArray`

2021-09-25 07:47 UTC, sidneyouteiro approved these changes

2021-09-25 07:47 UTC, merged