feat/editar
benhurfaria/projeto_11_linkr pull request #19
Opened 2021-09-23 03:59 UTC by benhurfaria

editar um post

2021-09-23 13:03 UTC, Audamon requested changes
Parece ok só resolve esse conflito da Api

2021-09-23 23:12 UTC, Audamon approved these changes

2021-09-24 12:44 UTC, sidneyouteiro requested changes

2021-09-24 12:44 UTC, sidneyouteiro commented on src/Timeline/PostsList/SinglePost.js
> +        mudarDescricaoPost(id, {"text": textDescription.value}, config, setInputHabilitado, setEdit, setTexto, text,edit, setTextoSucesso);
É uma boa deixarmos as funções do service retornando a promise e manipularmos o que acontecerá em seguida no respectivo componente com o `.then` e `.catch`
Assim reduzimos a quantidade de argumentos que precisaremos passar, e evitarmos precisar ficar indo de um arquivo para outro para entendermos quais mudanças serão feitas em cada state

2021-09-24 12:44 UTC, sidneyouteiro commented on src/Timeline/PostsList/SinglePost.js
> +                        }
`{ linkImage && <img src={linkImage} alt="thumbnail" /> }`

2021-09-24 12:44 UTC, sidneyouteiro commented on src/Timeline/PostsList/SinglePost.js
> +            }/>
As únicas diferenças entre um post do usuário logado para os posts dos demais usuários é a presença do icone de edição e suas funcionalidades. Na linha 61, ao invés de criarmos 2 versões da mesma postagem nesse if e else podemos usar a mesma lógica que usou para determinar se terá campo de edição de texto ou a própria descrição do post (linhas 61~70).
`{loggedUser.username === user.username && <BsPencil ...}`
E outra coisa, poderíamos transformar essa arrow function no onClick para uma função mesmo sem argumentos para reduzir o tamanho da tag e só passarmos o nome da função no onClick

2021-09-25 07:53 UTC, sidneyouteiro commented
Basta resolver os conflitos de merge e eu irei aprovar

2021-09-25 21:17 UTC, sidneyouteiro approved these changes

2021-09-25 21:17 UTC, merged