Infinite Scroll
benhurfaria/projeto_11_linkr pull request #20
Opened 2021-09-23 17:17 UTC by Audamon

2021-09-23 23:21 UTC, teles-tarcisio commented
@Audamon , tem uns posts na rolagem que parecem estar vindo repetidos, mas eu não tô conseguindo ver se estão realmente sendo renderizados repetidos ou se a galera realmente postou vários iguais em sequencia.

2021-09-23 23:25 UTC, teles-tarcisio requested changes
@Audamon , retestei e uma vez que o usuario rola a página uma vez, ela fica fazendo requisição direto pro servidor mesmo se não tiver mais rolagem. tá literalmente "infinito"

2021-09-24 20:42 UTC, teles-tarcisio commented
conferi a numeração dos posts, fiz alguns testes e parece estar tudo certo, ficou massa!

2021-09-24 20:43 UTC, teles-tarcisio approved these changes

2021-09-25 08:49 UTC, sidneyouteiro requested changes

2021-09-25 08:49 UTC, sidneyouteiro commented on src/Timeline/PostsList/Likes/PeoplesLikes.js
>  export { peoplesLikes }
Isso não faz parte da tarefa. E eu testei os likes e sempre que tem +3 curtidas e eu curta e descurta, os nomes que ficam no tooltip ficam como `undefined`. Acredito que foram realizadas algumas alterações naquele código que eu mandei e talvez essas mudanças podem estar causando o comportamento inesperado

2021-09-25 08:49 UTC, sidneyouteiro commented on src/Timeline/Timeline.js
> +                        hasMore={true || false}
Enquanto eu fiz uns testes, seria uma boa ter esse atributo controlado por um estado, pois quando acabarem as postagens o final da página ficará em um eterno loading

2021-09-25 08:49 UTC, sidneyouteiro commented on src/Timeline/Timeline.js
> +    }
if(loading) return ( 
            <LoaderPosition>
                          <Loader type="TailSpin" color="#6d6d6d" height={60} width={60} />Loading more posts...
            </LoaderPosition>)

2021-09-27 20:06 UTC, sidneyouteiro approved these changes

2021-09-27 20:06 UTC, merged