Feat /my posts
benhurfaria/projeto_11_linkr pull request #8
Opened 2021-09-18 21:02 UTC by teles-tarcisio

2021-09-18 23:36 UTC, sidneyouteiro requested changes
As mudanças que eu sugeri vão ajudar na realização das demais tarefas

2021-09-18 23:36 UTC, sidneyouteiro commented on src/Timeline/Timeline.js
Remover o comentário

2021-09-18 23:36 UTC, sidneyouteiro commented on src/Timeline/PostsList/PostsList.js
> +        }
Como a única diferença de entre as renderizações, é a presença do componente `NewPost` poderíamos ao invés de passar uma variável contendo uma string, poderíamos passar uma variável booleana do tipo `hasNewPostBox` e usar um ternário para verificar se renderizaríamos ou não o componente `NewPost`.

2021-09-19 23:49 UTC, teles-tarcisio commented on src/Timeline/PostsList/PostsList.js
> +        }
Mas Sidney, mais à frente vai ter a renderização só dos "my-likes", e aí essa variável poderá assumir mais um valor, algo do tipo: "timeline" , "my posts" , "my likes" e a renderização mudaria. o parâmetro tbm é usado pra saber qual a requisição a ser feita à API

2021-09-20 01:42 UTC, sidneyouteiro commented on src/Timeline/PostsList/PostsList.js
> +        }
Justo

2021-09-20 01:42 UTC, sidneyouteiro approved these changes

2021-09-20 01:44 UTC, merged